### ISSUE TITLE
Embedding links in flowchart to individual sections

### ISSUE THREAD

**Issue by smjasper3** [smjasper3/TRTADSF#2]
[https://stackoverflow.com/questions/45360998/code-folding-in-bookdown](https://stackoverflow.com/questions/45360998/code-folding-in-bookdown
)
-Also change font color to blue for nodes that link to other sections

**Comment by jocundjackson** [comment]
Huzzah! Example for doing this in graphviz. Should have dug deeper:


  node1 [style=filled, URL="https://www.vangoghmuseum.nl/en/collection/s0016V1962"]

**Comment by jocundjackson** [comment]
Me learning to RTFM: https://graphviz.org/docs/attrs/URL/
