### ISSUE TITLE
Add color/shading to flowchart

### ISSUE THREAD

**Issue by smjasper3** [smjasper3/TRTADSF#4]
-Green box for starting box
-Classify by color (i.e., decision diamonds are yellow)

**Comment by jocundjackson** [comment]
Notes for how to accomplish:

  node [shape=box, color=cornflowerblue]
  node2 [style=dotted, fillcolor=beige]

**Comment by jocundjackson** [comment]
https://github.com/smjasper3/TRTADSF/commit/7fc4373ae97044d94e76735e7ebe205bac813b97
